Задание 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [1]:
import numpy as np

In [21]:
b = np.array([1,2,3,3,1]).reshape(5,1)
c = np.array([6,8,11,10,7]).reshape(5,1)
              
a = np.hstack((b,c))
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [18]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

Задание 2
Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [20]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [30]:
a_centered_sp = np.dot(a_centered[:,0], a_centered[:,1]) / (len(a_centered[:,0])-1)
a_centered_sp


2.0

Задание 4*
В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [31]:
cov = np.cov(a.T)
cov

array([[1. , 2. ],
       [2. , 4.3]])

Задание 5**
Необходимо реализовать метод сортировки целых (int) элементов. Метод должен быть реализован без использования “готовых” методов ( sorted, np.sort() ).

In [36]:
# сортировка методом пузырька
from random import randint

def sort_bubble(numbers):
    for j in range(1, len(numbers)):
        count = 0
        for i in range(len(numbers)-j):
            # print(i)
            if numbers[i] > numbers[i+1]:  # если последующий меньше предыдущего
                numbers[i], numbers[i + 1] = numbers[i + 1], numbers[i]  # меняем местами
                count += 1
        if count == 0:  # если массив уже отсортирован досрочно выходим из функции
            # print(j, i)
            # print("already sorted")
            return numbers
    return numbers

nums  = np.random.randint(0, 20, 10)
print(nums)

print(sort_bubble(nums))


[18  3  4  9 11  8  5  4  2 11]
[ 2  3  4  4  5  8  9 11 11 18]
